kas-project.yml: remove repo meta-custom
According to the user guide[1]:

	* repos: dict [optional]

	Contains the definitions of all available repos and layers.

	 - <repo-id>: dict [optional]

	Contains the definition of a repository and the layers, that
	should be part of the build. If the value is None, the
	repository, where the current configuration file is located is
	defined as <repo-id> and added as a layer to the build. It is
	recommended that the <repo-id> is related to the containing
	repository/layer to ease cross-project referencing.

	(...)

	  + path: string [optional]

	The path where the repository is stored. If the url and path is
	missing, the repository where the current configuration file is
	located is defined.

The layer repository meta-custom defined by the configuration file
example is the repository itself.

The repository is **NOT** a layer; it is a builder repository based on
the kas project.

Therefore, it **DOES NOT** and **WILL NOT** contain a OpenEmbedded layer
configuration file[1][2].

This removes the meta-custom from the repositories.

Fixes:

	$ kas build kas-project.yml
	2023-09-02 01:46:28 - INFO     - kas 4.0 started
	2023-09-02 01:46:28 - WARNING  - kas: No supported distros found in ['arch']. No default locales set.
	2023-09-02 01:46:28 - INFO     - /home/gportay/src/kaspokypi$ git rev-parse --show-toplevel
	2023-09-02 01:46:28 - INFO     - /home/gportay/src/kaspokypi$ git rev-parse --show-toplevel
	2023-09-02 01:46:28 - INFO     - /home/gportay/src/kaspokypi$ git rev-parse --show-toplevel
	2023-09-02 01:46:28 - INFO     - Using /home/gportay/src/kaspokypi as root for repository meta-custom
	2023-09-02 01:46:28 - INFO     - /home/gportay/src/kaspokypi$ git clone -q https://git.yoctoproject.org/git/poky /home/gportay/src/kaspokypi/poky
	2023-09-02 01:47:23 - INFO     - Repository poky cloned
	2023-09-02 01:47:23 - INFO     - /home/gportay/src/kaspokypi/poky$ git remote set-url origin https://git.yoctoproject.org/git/poky
	2023-09-02 01:47:23 - INFO     - /home/gportay/src/kaspokypi/poky$ git cat-file -t kirkstone
	2023-09-02 01:47:23 - INFO     - /home/gportay/src/kaspokypi/poky$ git fetch -q
	2023-09-02 01:47:23 - INFO     - Repository poky updated
	2023-09-02 01:47:23 - INFO     - /home/gportay/src/kaspokypi$ git rev-parse --show-toplevel
	2023-09-02 01:47:23 - INFO     - Using /home/gportay/src/kaspokypi as root for repository meta-custom
	2023-09-02 01:47:23 - INFO     - /home/gportay/src/kaspokypi/poky$ git status -s
	2023-09-02 01:47:24 - INFO     - /home/gportay/src/kaspokypi/poky$ git checkout -q kirkstone
	2023-09-02 01:47:27 - INFO     - /home/gportay/src/kaspokypi$ git rev-parse --show-toplevel
	2023-09-02 01:47:27 - INFO     - Using /home/gportay/src/kaspokypi as root for repository meta-custom
	2023-09-02 01:47:27 - INFO     - /home/gportay/src/kaspokypi$ git rev-parse --show-toplevel
	2023-09-02 01:47:27 - INFO     - Using /home/gportay/src/kaspokypi as root for repository meta-custom
	2023-09-02 01:47:27 - INFO     - /home/gportay/src/kaspokypi/poky$ /tmp/tmps4odsw1w/get_bb_env /home/gportay/src/kaspokypi/build
	2023-09-02 01:47:27 - INFO     - /home/gportay/src/kaspokypi$ git rev-parse --show-toplevel
	2023-09-02 01:47:28 - INFO     - Using /home/gportay/src/kaspokypi as root for repository meta-custom
	2023-09-02 01:47:28 - INFO     - /home/gportay/src/kaspokypi/build$ /home/gportay/src/kaspokypi/poky/bitbake/bin/bitbake -c build core-image-minimal
	ERROR: Unable to parse /home/gportay/src/kaspokypi/poky/bitbake/lib/bb/parse/__init__.py
	Traceback (most recent call last):
	  File "/home/gportay/src/kaspokypi/poky/bitbake/lib/bb/parse/__init__.py", line 133, in resolve_file(fn='/home/gportay/src/kaspokypi/build/../conf/layer.conf', d=<bb.data_smart.DataSmart object at 0x7fef48d47150>):
	         if not os.path.isfile(fn):
	    >        raise IOError(errno.ENOENT, "file %s not found" % fn)

	FileNotFoundError: [Errno 2] file /home/gportay/src/kaspokypi/build/../conf/layer.conf not found

	2023-09-02 01:47:34 - ERROR    - Command "/home/gportay/src/kaspokypi/poky/bitbake/bin/bitbake -c build core-image-minimal" failed with error 1

[1]: https://kas.readthedocs.io/en/4.0/userguide.html#configuration-reference
[2]: https://docs.yoctoproject.org/dev/overview-manual/yp-intro.html#the-yocto-project-layer-model
[3]: https://docs.yoctoproject.org/dev/dev-manual/layers.html#understanding-and-creating-layers